name: advent
version: 1.0.0
github: dpca/advent-of-code-2021
license: MIT
author: Dan Cahoon

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - split
  - containers

executable:
  main: Main.hs
  source-dirs: src

tests:
  unit:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - hspec
